kind: Pod
apiVersion: v1
metadata:
  name: busybox-node-b
  namespace: default
  labels:
    app: client
    node: node-b
spec:
  containers:
  - name: client
    image: busybox
    imageTag: latest
    command: ["sh", "-c"]
    args: ["sleep 3600"]
  restartPolicy: Always
