kind: Pod
apiVersion: v1
metadata:
  name: nginx-node-b
  namespace: default
  labels:
    app: nginx
    tier: frontend
spec:
  nodeSelector:
    node: node-b
  containers:
  - name: nginx
    image: nginx
    imageTag: 1.27-alpine
    command: ["nginx"]
    args: ["-g", "daemon off;"]
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: "0.1"
        memory: "64Mi"
      limits:
        cpu: "0.5"
        memory: "128Mi"
  restartPolicy: Always
