kind: Pod
apiVersion: v1
metadata:
  name: busybox-client
  namespace: default
  labels:
    app: client
spec:
  containers:
  - name: client
    image: busybox
    imageTag: 1.36
    command: ["sh", "-c"]
    args: ["sleep 3600"]
  restartPolicy: Always
