kind: Service
apiVersion: v1
metadata:
  name: rs-05-hpa
  namespace: default
  labels:
    app: rs-05-hpa
    case: minik8s-acceptance-05
spec:
  type: NodePort
  selector:
    matchLabels:
      app: rs-05-hpa
      case: minik8s-acceptance-05
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30082
