kind: EventTrigger
apiVersion: v1
metadata:
  name: text-branch-events
  labels:
    app: serverless-demo
spec:
  subject: minik8s.text.branch
  replySubject: minik8s.text.branch.reply
  workflowRef:
    name: text-branch
