kind: Function
apiVersion: v1
metadata:
  name: slow-echo
  labels:
    app: serverless-demo
spec:
  runtime: python
  handler: handler
  port: 8080
  minReplicas: 0
  maxReplicas: 3
  targetConcurrency: 1
  idleTimeoutSeconds: 30
  code: |
    import time

    def handler(event):
      time.sleep(5)
      return event
