kind: Workflow
apiVersion: v1
metadata:
  name: process-one-image
  labels:
    app: image-workflow
spec:
  steps:
  - name: extract-metadata
    functionRef:
      name: extract-metadata
  - name: sam-segment
    functionRef:
      name: sam-segment
  - name: score-mask
    functionRef:
      name: score-mask
