kind: Pod
apiVersion: v1
metadata:
  name: nginx-rs-manual
  namespace: default
  labels:
    app: nginx-rs
    tier: manual
spec:
  containers:
  - name: nginx
    image: nginx
    imageTag: alpine
    command: ["nginx"]
    args: ["-g", "daemon off;"]
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: "100m"
        memory: "64Mi"
      limits:
        cpu: "500m"
        memory: "128Mi"
  restartPolicy: Always
