package dnssync

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	store "minik8s/internal/bridge/logbook"
	"minik8s/internal/routeproxy"
	"minik8s/internal/service"
)

type Config struct {
	DNSStore     store.DNSStore
	ServiceStore store.ServiceStore
	GatewayIP    string
	HostsPath    string
	RoutesPath   string
}

func Sync(ctx context.Context, config Config) error {
	_ = ctx
	if config.DNSStore == nil {
		return fmt.Errorf("dns store is required")
	}
	if config.ServiceStore == nil {
		return fmt.Errorf("service store is required")
	}
	items, err := config.DNSStore.List("", nil)
	if err != nil {
		return fmt.Errorf("listing dns: %w", err)
	}
	services, err := config.ServiceStore.List("", nil)
	if err != nil {
		return fmt.Errorf("listing services: %w", err)
	}
	serviceByKey := make(map[string]*service.Service, len(services))
	for _, svc := range services {
		serviceByKey[key(svc.Namespace, svc.Name)] = svc
	}
	sort.Slice(items, func(i, j int) bool {
		return key(items[i].Namespace, items[i].Name) < key(items[j].Namespace, items[j].Name)
	})
	snapshot := routeproxy.Snapshot{Hosts: make([]routeproxy.HostRoute, 0, len(items))}
	hosts := make([]string, 0, len(items))
	for _, d := range items {
		host := strings.TrimSpace(d.Spec.Host)
		if host == "" {
			continue
		}
		hosts = append(hosts, fmt.Sprintf("%s %s", config.GatewayIP, host))
		hostRoute := routeproxy.HostRoute{Host: host, Namespace: d.Namespace, Paths: make([]routeproxy.PathRoute, 0, len(d.Spec.Paths))}
		for _, p := range d.Spec.Paths {
			route := routeproxy.PathRoute{
				Path:        p.Path,
				PathType:    string(p.PathType),
				Service:     p.ServiceName,
				ServicePort: p.ServicePort,
			}
			if svc, ok := serviceByKey[key(d.Namespace, p.ServiceName)]; ok {
				route.Endpoints = endpointsForPort(svc, p.ServicePort)
			}
			hostRoute.Paths = append(hostRoute.Paths, route)
		}
		snapshot.Hosts = append(snapshot.Hosts, hostRoute)
	}
	if err := writeHosts(config.HostsPath, hosts); err != nil {
		return err
	}
	return writeJSON(config.RoutesPath, snapshot)
}

func endpointsForPort(svc *service.Service, port int32) []routeproxy.Endpoint {
	endpoints := make([]routeproxy.Endpoint, 0, len(svc.Status.Endpoints))
	for _, endpoint := range svc.Status.Endpoints {
		if endpoint.Port != port {
			continue
		}
		endpoints = append(endpoints, routeproxy.Endpoint{IP: endpoint.IP, Port: endpoint.TargetPort})
	}
	return endpoints
}

func writeHosts(path string, hosts []string) error {
	sort.Strings(hosts)
	data := "# generated by minik8s dns-sync\n" + strings.Join(hosts, "\n") + "\n"
	return writeFile(path, []byte(data))
}

func writeJSON(path string, value any) error {
	data, err := json.MarshalIndent(value, "", "  ")
	if err != nil {
		return err
	}
	data = append(data, '\n')
	return writeFile(path, data)
}

func writeFile(path string, data []byte) error {
	if path == "" {
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, data, 0o644); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}

func key(namespace, name string) string {
	if namespace == "" {
		namespace = "default"
	}
	return namespace + "/" + name
}
