kind: Service
apiVersion: v1
metadata:
  name: nginx-nodeport
  namespace: default
  labels:
    app: nginx
    tier: frontend
spec:
  type: NodePort
  selector:
    matchLabels:
      app: nginx
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
