#!/usr/bin/env bash

# Source this file on the target machine before running acceptance scripts:
#   source scripts/acceptance/env.sh
#
# This file defines runtime/test variables only. It deliberately does not set
# SSH targets or private-key paths because acceptance scripts run on the target
# machines themselves.

export MINIK8S_REMOTE_DIR="${MINIK8S_REMOTE_DIR:-/opt/minik8s}"

export NO_COLOR="${NO_COLOR:-1}"
export MINIK8S_PLAIN="${MINIK8S_PLAIN:-1}"

export MINIK8S_NODE_A_NAME="${MINIK8S_NODE_A_NAME:-node-a}"
export MINIK8S_NODE_B_NAME="${MINIK8S_NODE_B_NAME:-node-b}"
export MINIK8S_NODE_C_NAME="${MINIK8S_NODE_C_NAME:-node-c}"
export MINIK8S_NODE_A_IP="${MINIK8S_NODE_A_IP:-192.168.1.4}"
export MINIK8S_NODE_B_IP="${MINIK8S_NODE_B_IP:-192.168.1.10}"
export MINIK8S_NODE_C_IP="${MINIK8S_NODE_C_IP:-192.168.1.15}"

export MINIK8S_HARBOR_PORT="${MINIK8S_HARBOR_PORT:-18080}"
export MINIK8S_HARBOR="${MINIK8S_HARBOR:-http://$MINIK8S_NODE_A_IP:$MINIK8S_HARBOR_PORT}"
export MINIK8S_DNS_PORT="${MINIK8S_DNS_PORT:-153}"

export MINIK8S_TOKEN="${MINIK8S_TOKEN:-minik8s}"

export MINIK8S_CLUSTER_CIDR="${MINIK8S_CLUSTER_CIDR:-10.244.0.0/16}"
export MINIK8S_SERVICE_CIDR="${MINIK8S_SERVICE_CIDR:-10.96.0.0/12}"
export MINIK8S_NODE_PORT_RANGE="${MINIK8S_NODE_PORT_RANGE:-30000-32767}"
export MINIK8S_VXLAN_PORT="${MINIK8S_VXLAN_PORT:-4789}"

export MINIK8S_CNI_CONF_DIR="${MINIK8S_CNI_CONF_DIR:-/etc/cni/net.d}"
export MINIK8S_CNI_BIN_DIR="${MINIK8S_CNI_BIN_DIR:-/opt/cni/bin}"
export MINIK8S_CNI_DISABLED="${MINIK8S_CNI_DISABLED:-0}"
export MINIK8S_STATE_DIR="${MINIK8S_STATE_DIR:-$MINIK8S_REMOTE_DIR/state}"

minik8s_acceptance_env_print() {
  cat <<EOF
MINIK8S_REMOTE_DIR=$MINIK8S_REMOTE_DIR
NO_COLOR=$NO_COLOR
MINIK8S_PLAIN=$MINIK8S_PLAIN
MINIK8S_NODE_A_NAME=$MINIK8S_NODE_A_NAME
MINIK8S_NODE_A_IP=$MINIK8S_NODE_A_IP
MINIK8S_NODE_B_NAME=$MINIK8S_NODE_B_NAME
MINIK8S_NODE_B_IP=$MINIK8S_NODE_B_IP
MINIK8S_NODE_C_NAME=$MINIK8S_NODE_C_NAME
MINIK8S_NODE_C_IP=$MINIK8S_NODE_C_IP
MINIK8S_HARBOR_PORT=$MINIK8S_HARBOR_PORT
MINIK8S_HARBOR=$MINIK8S_HARBOR
MINIK8S_DNS_PORT=$MINIK8S_DNS_PORT
MINIK8S_TOKEN=$MINIK8S_TOKEN
MINIK8S_CLUSTER_CIDR=$MINIK8S_CLUSTER_CIDR
MINIK8S_SERVICE_CIDR=$MINIK8S_SERVICE_CIDR
MINIK8S_NODE_PORT_RANGE=$MINIK8S_NODE_PORT_RANGE
MINIK8S_VXLAN_PORT=$MINIK8S_VXLAN_PORT
MINIK8S_CNI_CONF_DIR=$MINIK8S_CNI_CONF_DIR
MINIK8S_CNI_BIN_DIR=$MINIK8S_CNI_BIN_DIR
MINIK8S_CNI_DISABLED=$MINIK8S_CNI_DISABLED
MINIK8S_STATE_DIR=$MINIK8S_STATE_DIR
EOF
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  minik8s_acceptance_env_print
fi
