kind: HorizontalPodAutoscaler
apiVersion: v1
metadata:
  name: hpa-05-web
  namespace: default
  labels:
    app: rs-05-hpa
    case: minik8s-acceptance-05
spec:
  scaleTargetRef:
    kind: ReplicaSet
    name: rs-05-hpa
  minReplicas: 1
  maxReplicas: 3
  behavior:
    syncIntervalSeconds: 5
    scaleUp:
      maxReplicaDeltaPerSync: 2
    scaleDown:
      maxReplicaDeltaPerSync: 2
      cooldownSeconds: 0
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 10000
